// <auto-generated />
using JuninViagens.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuninViagens.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240110152658_Primeira")]
    partial class Primeira
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JuninViagens.Model.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("EmailCli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("cepCli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("enderecoCli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomeCli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailCli = "junio@gmail",
                            cepCli = "454545",
                            enderecoCli = "rua amilton 13",
                            nomeCli = "Junio"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
